(function(){
'use strict';
const get=id=>document.getElementById(id);let source=null,changes=new Map(),ready=null,generation=0;
function clearReady(){ready=null;get('maker-preview-result').hidden=true;get('maker-save').disabled=true;}
function updateLoad(){get('maker-load').disabled=!(get('original').files.length&&get('maker-source-confirm').checked);}
function reset(){generation++;source=null;changes.clear();clearReady();get('maker-editor').hidden=true;get('maker-fields').replaceChildren();get('maker-source-confirm').checked=false;get('maker-state').textContent='元CSVを選び、取得元を確認すると編集できます。';updateLoad();}
for(const id of ['original','encoding'])get(id).addEventListener('change',reset);get('clear').addEventListener('click',reset);
get('maker-source-confirm').addEventListener('change',()=>{if(!get('maker-source-confirm').checked){generation++;source=null;changes.clear();clearReady();get('maker-editor').hidden=true;}updateLoad();});
function showRow(){clearReady();get('maker-fields').replaceChildren();if(!source)return;const row=Number(get('maker-row').value),item=source.table.data[row-2];get('maker-reason').textContent='元CSV '+row+'行目のエラー理由：'+(item['エラー理由']||'記載なし');
 for(const field of RetryMaker.fields){const label=document.createElement('label');label.textContent=field;const input=document.createElement('input');input.type='text';input.maxLength=100;input.value=changes.get(row+'|'+field)?.value??item[field];label.append(input);get('maker-fields').append(label);input.addEventListener('input',()=>{clearReady();const key=row+'|'+field;if(input.value===item[field])changes.delete(key);else changes.set(key,{row,field,value:input.value});get('maker-state').textContent='修正値を変更しました。保存前に保全を確認してください。';});}
}
get('maker-row').addEventListener('change',showRow);
get('maker-load').addEventListener('click',async()=>{if(!get('maker-source-confirm').checked)return;const file=get('original').files[0];if(!file)return;const token=++generation,encoding=get('encoding').value;source=null;changes.clear();clearReady();get('maker-editor').hidden=true;get('maker-state').textContent='元CSVを端末内で読み取り中…';try{if(file.size>12000000)throw Error('元CSVは12MBまでです。');const bytes=new Uint8Array(await file.arrayBuffer()),text=new TextDecoder(encoding,{fatal:true,ignoreBOM:true}).decode(bytes),table=RetryCheck.table(text);if(token!==generation)return;const failed=table.data.map((r,i)=>r['処理結果']==='失敗'?i+2:null).filter(r=>r!==null);if(!failed.length)throw Error('失敗行がありません。成功行は変更しません。');source={bytes,text,encoding,table};get('maker-row').replaceChildren();for(const row of failed){const o=document.createElement('option');o.value=String(row);o.textContent='CSV '+row+'行目';get('maker-row').append(o);}get('maker-row').value=String(failed[0]);showRow();get('maker-editor').hidden=false;get('maker-state').textContent=failed.length+'件の失敗行から、必要な欄だけを自分で修正してください。';}catch(error){if(token!==generation)return;source=null;get('maker-state').textContent='読み取れませんでした。 '+error.message;}});
get('maker-preview').addEventListener('click',()=>{clearReady();if(!source)return;try{ready=RetryMaker.applyBytes(source.bytes,source.encoding,[...changes.values()],RetryCheck);get('maker-summary').textContent='保全一致：成功行・行順・非許可欄を保っています。変更した失敗行 '+ready.comparison.edits.length+'件、変更欄 '+ready.edits.length+'件。文字コード '+(source.encoding==='utf-8'?'UTF-8':'S-JIS')+'。価格・日時の公式受理や失敗原因の解消は未確認です。';get('maker-preview-result').hidden=false;get('maker-save').disabled=false;get('maker-state').textContent='新CSVを保存できます。原本は書き換えません。';}catch(error){get('maker-state').textContent='保存を保留しました。 '+error.message;}});
get('maker-save').addEventListener('click',()=>{if(!ready||!source||!get('maker-source-confirm').checked)return;const blob=new Blob([ready.bytes],{type:'text/csv;charset='+source.encoding}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='timesale-explicit-edits-'+(source.encoding==='utf-8'?'utf8':'sjis')+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);get('maker-state').textContent='新CSVを保存しました。上の2ファイル比較でも確認し、原典・管理画面の条件と受理結果を別に確認してください。';});updateLoad();
})();
