'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),S=require('./logic.js');
const raw=JSON.parse(fs.readFileSync(__dirname+'/sample.json','utf8')),m=S.validateModel(raw),clone=x=>JSON.parse(JSON.stringify(x)),cart={country:'JP',subtotal_minor:5000,weight_g:500};let tests=0;
function test(name,f){f();tests++;console.log('ok '+name);}
test('all matching options, no silent free selection',()=>{let r=S.check(m,cart);assert.deepEqual(r.matches.map(x=>x.id),['free','express']);assert.deepEqual(r.flags,['multiple_options']);});
test('price boundaries exact inclusive',()=>{assert.deepEqual(S.check(m,{...cart,subtotal_minor:4999}).matches.map(x=>x.id),['standard','express']);assert.deepEqual(S.check(m,{...cart,subtotal_minor:5001}).matches.map(x=>x.id),['free','express']);});
test('weight max at and above exposes gap',()=>{assert.equal(S.check(m,{...cart,weight_g:2000}).matches.length,2);assert.deepEqual(S.check(m,{...cart,weight_g:2001}).flags,['gap']);});
test('unknown country is not eligibility verdict',()=>{assert.deepEqual(S.check(m,{...cart,country:'US'}).flags,['country_not_in_entered_model','gap']);});
test('invalid imported models rejected',()=>{for(let change of [x=>x.currency='EUR',x=>x.zones[0].rates[0].price_minor=1.1,x=>x.zones[0].rates[0].weight_g.max=-1,x=>x.zones[0].rates[0].subtotal_minor.min=5000,x=>x.zones[0].countries.push('JP'),x=>x.zones[0].rates[1].id='standard',x=>x.extra='x',x=>x.zones[0].rates[0].price_minor=1000000001]){const x=clone(raw);change(x);assert.throws(()=>S.validateModel(x));}assert.throws(()=>S.parse(' '.repeat(S.MAX+1)));});
test('100 rule limit',()=>{const x=clone(raw);x.zones[0].rates=Array.from({length:101},(_,i)=>({...clone(x.zones[0].rates[0]),id:'r'+i}));assert.throws(()=>S.validateModel(x));});
test('200 bounded coverage and omitted count',()=>{const x=clone(raw);x.zones[0].rates=Array.from({length:100},(_,i)=>({...clone(x.zones[0].rates[0]),id:'r'+i,subtotal_minor:{min:i*10,max:i*10+5},weight_g:{min:i*10,max:i*10+5}}));let g=S.scenarios(S.validateModel(x));assert.equal(g.cases.length,200);assert.ok(g.coverage.omitted_unique>0);assert.equal(g.coverage.complete_within_strategy,false);});
test('no expectation never gives a pass',()=>{let r=S.regression(m,null);assert.equal(r.status,'unconfirmed');assert.ok(r.rows.every(x=>x.comparison==='unconfirmed'));assert.ok(r.rows.some(x=>x.flags.includes('gap')));});
test('baseline replay uses old carts and catches altered price',()=>{let b=S.validateExpected(S.baseline(m));assert.equal(S.regression(m,b).status,'matches_generated_baseline');let next=clone(m);next.zones[0].rates[0].price_minor=650;let r=S.regression(S.validateModel(next),b);assert.equal(r.status,'mismatch');assert.deepEqual(r.rows.map(x=>x.cart),b.cases.map(x=>x.cart));});
test('owner-declared expectations remain qualified',()=>{let b=S.baseline(m);b.declaration_kind='owner_declared';b.declaration='Owner reviewed expected fixture identifiers and prices.';assert.equal(S.regression(m,S.validateExpected(b)).status,'matches_owner_declared_cases');});
test('invalid expected file stops rather than false pass',()=>{let b=S.baseline(m);b.cases[0].expected[0].price_minor=0.1;assert.throws(()=>S.validateExpected(b));b=S.baseline(m);b.currency='USD';assert.throws(()=>S.regression(m,S.validateExpected(b)));});
test('USD exact minor unit edge',()=>{let x=clone(raw);x.currency='USD';x.zones[0].rates[0].subtotal_minor={min:0,max:4999};const usd=S.validateModel(x);assert.equal(S.check(usd,{...cart,subtotal_minor:4999}).matches[0].id,'standard');assert.ok(S.scenarios(usd).cases.some(c=>c.cart.subtotal_minor===5001));});
test('CSV is bounded rows with quoted aliases',()=>{let r=S.regression(m);assert.equal(S.csv(r).split('\r\n').length,r.rows.length+1);assert.ok(S.csv(r).includes('"JPY"'));});
test('large matching sets still produce importable baseline and disclose omissions',()=>{let x=clone(raw);x.zones[0].rates=Array.from({length:100},(_,i)=>({...clone(x.zones[0].rates[0]),id:'r'+String(i).padStart(63,'0'),subtotal_minor:{min:i,max:null},weight_g:{min:0,max:null}}));let b=S.baseline(S.validateModel(x));assert.ok(new TextEncoder().encode(JSON.stringify(b,null,2)).length<=S.MAX);assert.ok(b.coverage.omitted_unique>0);assert.equal(b.coverage.complete_within_strategy,false);S.validateExpected(S.parse(JSON.stringify(b,null,2)));});
console.log(JSON.stringify({tests,status:'passed'}));
